CREATE DATABASE IF NOT EXISTS first;
USE first;
 CREATE TABLE IF NOT EXISTS `first` (`test` VARCHAR (20) NOT NULL  PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS `second` (`test` VARCHAR (20) NOT NULL  PRIMARY KEY) ENGINE = MyISAM;
    