CREATE DATABASE IF NOT EXISTS Database;
USE Database;
 CREATE TABLE IF NOT EXISTS Database.first (id INT (20) NOT NULL AUTO_INCREMENT ,name VARCHAR (50) NOT NULL  ) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.teacher (name INT (20) NOT NULL AUTO_INCREMENT ) ENGINE = MyISAM;
    