CREATE DATABASE IF NOT EXISTS Database;
USE Database;
 CREATE TABLE IF NOT EXISTS Database.first (col1 INT (20) NOT NULL  ) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first2 (col2 INT (20) NOT NULL AUTO_INCREMENT ) ENGINE = MyISAM;
    