CREATE DATABASE IF NOT EXISTS test;
USE test;
 CREATE TABLE IF NOT EXISTS test.student (id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR (50) NOT NULL  ) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS test.subject (id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY,name VARCHAR (50) NOT NULL  ) ENGINE = MyISAM;
    