CREATE DATABASE IF NOT EXISTS test;
USE test;
 CREATE TABLE IF NOT EXISTS test.student (name VARCHAR (50) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS test.subject (id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY,sub_name VARCHAR (60) NOT NULL  ) ENGINE = MyISAM;
    