CREATE DATABASE IF NOT EXISTS test2;
USE test2;
 CREATE TABLE IF NOT EXISTS `containers` (`container_id` INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,`container_no` VARCHAR (500) NOT NULL  ,`arrived_date` DATE  NOT NULL  ,`loadIng_date` DATE  NOT NULL  ,`shipped_date` DATE  NOT NULL  ,`status_id` INT (11) NOT NULL  ) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS `status` (`status_id` INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR (250) NOT NULL  ) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS `users` (`user_id` INT (11) NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_name` VARCHAR (250) NOT NULL  ,`password` VARCHAR (500) NOT NULL  ) ENGINE = MyISAM;
    