CREATE DATABASE IF NOT EXISTS test;
USE test;
 CREATE TABLE IF NOT EXISTS test.student (test DATE  NOT NULL  ,second VARCHAR (20) NOT NULL  ,thrid VARCHAR (20) NOT NULL  ,yesy VARCHAR (20) NOT NULL  ) ENGINE = MyISAM;
    