CREATE DATABASE IF NOT EXISTS userLogin;
USE userLogin;
 CREATE TABLE IF NOT EXISTS `user` (`user_id` INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR (200) NOT NULL  UNIQUE,`password` VARCHAR (200) NOT NULL  ) ENGINE = MyISAM;
    