CREATE DATABASE IF NOT EXISTS Database;
USE Database;
 CREATE TABLE IF NOT EXISTS Database.first (student VARCHAR (20) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first7 (test2 VARCHAR (20) NOT NULL  ,student VARCHAR (20) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first8 (test2 VARCHAR (20) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first9 (test2 VARCHAR (20) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first10 (student VARCHAR (20) NOT NULL  ,test2 VARCHAR (20) NOT NULL  ,id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    ;CREATE TABLE IF NOT EXISTS Database.first11 (id INT (20) NOT NULL AUTO_INCREMENT PRIMARY KEY) ENGINE = MyISAM;
    